### ISSUE TITLE
I want to disable sunday in week view and month view

### ISSUE THREAD

**Issue by rahul-rayo** [acro5piano/react-native-big-calendar#1095]

**Comment by acro5piano** [comment]
Good question. Please use `mode="custom"`, `weekStartsOn`, and `weekEndsOn`.

For details, please take a look at: 

https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/desktop.stories.tsx#L283-L293

Feel free to re-open if you have further questions.

**Comment by rahul-rayo** [comment]
@acro5piano  Thank you so much for your answer.
but I updated the code according to my need
and made PR.

**Comment by acro5piano** [comment]
Thank you for the PR, but I still don't understand why specifying both `weekStartsOn` and `weekEndsOn` doesn't meet your need.

https://react-native-big-calendar.vercel.app/?path=/story/showcase-desktop--custom-week-length

If you elabortate your needs more, I could merge your PR. Thanks.
